export enum BarriosBuenoAiresEnum {
  // --- ZONA NORTE ---
  ESCOBAR = 'Escobar',
  PILAR = 'Pilar',
  TIGRE = 'Tigre',
  SAN_FERNANDO = 'San Fernando',
  SAN_ISIDRO = 'San Isidro',
  VICENTE_LOPEZ = 'Vicente López',
  MALVINAS_ARGENTINAS = 'Malvinas Argentinas',
  JOSE_C_PAZ = 'José C. Paz',
  SAN_MIGUEL = 'San Miguel',
  GENERAL_SAN_MARTIN = 'General San Martín',

  // --- ZONA OESTE ---
  LA_MATANZA = 'La Matanza',
  TRES_DE_FEBRERO = 'Tres de Febrero',
  HURLINGHAM = 'HurlingHAM',
  ITUZAINGO = 'Ituzaingó',
  MORON = 'Morón',
  MERLO = 'Merlo',
  MORENO = 'Moreno',
  GENERAL_RODRIGUEZ = 'General Rodríguez',
  MARCOS_PAZ = 'Marcos Paz',

  // --- ZONA SUR ---
  AVELLANEDA = 'Avellaneda',
  LANUS = 'Lanús',
  LOMAS_DE_ZAMORA = 'Lomas de Zamora',
  ALMIRANTE_BROWN = 'Almirante Brown',
  QUILMES = 'Quilmes',
  BERAZATEGUI = 'Berazategui',
  FLORENCIO_VARELA = 'Florencio Varela',
  ESTEBAN_ECHEVERRIA = 'Esteban Echeverría',
  EZEIZA = 'Ezeiza',
  EZPELETA_BERISSO = 'Berisso', 
  ENSENADA = 'Ensenada',       
  LA_PLATA = 'La Plata',
  SAN_VICENTE = 'San Vicente',
  PRESIDENTE_PERON = 'Presidente Perón',
  CANUELAS = 'Cañuelas',
}